const projects = [
  {
    id: 1,
    slug: 'taskflow-landing',
    title: 'TaskFlow – SaaS Landing Page',
    category: 'Landing Page',
    thumbnail: '/images/taskflow.jpg',
    description: 'A high-end, animated landing page for a fictional productivity SaaS. Built with semantic HTML, modular SCSS, and GSAP animations.',
    tech: ['HTML5', 'SCSS (BEM)', 'JavaScript', 'GSAP'],
    liveUrl: 'https://taskflow-demo.netlify.app',
    codeUrl: 'https://github.com/quim-romero/taskflow-landing',
  },
  {
    id: 2,
    slug: 'lumen-portfolio',
    title: 'Lumen Studio – Digital Artist Portfolio',
    category: 'Interactive Gallery',
    thumbnail: '/images/lumen.jpg',
    description: 'Elegant, animated microsite for a digital artist. Includes gallery with filters, dark mode toggle, and scroll animations using AOS.js.',
    tech: ['HTML5', 'CSS Grid', 'JavaScript', 'AOS.js'],
    liveUrl: 'https://lumen-portfolio.netlify.app',
    codeUrl: 'https://github.com/quim-romero/lumen-portfolio',
  },
  {
    id: 3,
    slug: 'devsummit-landing',
    title: 'DevSummit 2025 – Event Landing Page',
    category: 'Tailwind',
    thumbnail: '/images/devsummit.jpg',
    description: 'Lightning-fast landing built with Tailwind CSS. Mobile-first layout, custom components, dark mode and GSAP interactions.',
    tech: ['Tailwind CSS', 'Alpine.js', 'GSAP'],
    liveUrl: 'https://devsummit-landing.netlify.app',
    codeUrl: 'https://github.com/quim-romero/devsummit-landing',
  },
  {
    id: 4,
    slug: 'visionary-gallery',
    title: 'Visionary Gallery – Art SPA',
    category: 'SPA',
    thumbnail: '/images/visionary.jpg',
    description: 'Full SPA built with React to showcase digital artworks. Features filters, modals, lazy loading, routing, and animated transitions.',
    tech: ['React', 'React Router', 'Tailwind', 'Framer Motion'],
    liveUrl: 'https://visionary-gallery.netlify.app',
    codeUrl: 'https://github.com/quim-romero/visionary-gallery',
  },
  {
    id: 5,
    slug: 'trackforge-dashboard',
    title: 'TrackForge – Productivity Dashboard',
    category: 'Dashboard',
    thumbnail: '/images/trackforge.jpg',
    description: 'Functional dashboard with task management, charts, filters, and global state. Built with React + TypeScript and Zustand.',
    tech: ['React', 'TypeScript', 'Tailwind CSS', 'Zustand', 'Chart.js'],
    liveUrl: 'https://trackforge-dashboard.netlify.app',
    codeUrl: 'https://github.com/quim-romero/trackforge-dashboard',
  },
  {
    id: 6,
    slug: 'nebulaos-microsite',
    title: 'NebulaOS – Interactive Product Microsite',
    category: 'Animated Story',
    thumbnail: '/images/nebulaos.jpg',
    description: 'Scroll-driven storytelling experience for a futuristic digital product. Uses Framer Motion, custom modals, and smooth scroll techniques.',
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'Lenis.js'],
    liveUrl: 'https://nebulaos.netlify.app',
    codeUrl: 'https://github.com/quim-romero/nebulaos-microsite',
  },
  {
    id: 7,
    slug: 'novatech-solutions',
    title: 'NovaTech – Corporate Multipage Website',
    category: 'Full Website',
    thumbnail: '/images/novatech.jpg',
    description: 'A complete company website with multiple pages, animated sections, routing, forms and responsive design. Built with React and Framer Motion.',
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'React Helmet'],
    liveUrl: 'https://novatech-solutions.netlify.app',
    codeUrl: 'https://github.com/quim-romero/novatech-solutions',
  },
]

export default projects
